import { KeyBinding, KeyLoc } from './Key';
import { Keymap } from './Keymap';

const corneMatrix: KeyLoc[] = [
  { x: -7, y: -0.75 },
  { x: -6, y: -0.75 },
  { x: -5, y: -1 },
  { x: -4, y: -1.125 },
  { x: -3, y: -1 },
  { x: -2, y: -0.875 },
  { x: -1, y: -0.375 },
  { x: 1, y: -0.375 },
  { x: 2, y: -0.875 },
  { x: 3, y: -1 },
  { x: 4, y: -1.125 },
  { x: 5, y: -1 },
  { x: 6, y: -0.75 },
  { x: 7, y: -0.75 },

  { x: -7, y: 0.25 },
  { x: -6, y: 0.25 },
  { x: -5, y: 0 },
  { x: -4, y: -0.125 },
  { x: -3, y: 0 },
  { x: -2, y: 0.125 },
  { x: -1, y: 0.625 },
  { x: 1, y: 0.625 },
  { x: 2, y: 0.125 },
  { x: 3, y: 0 },
  { x: 4, y: -0.125 },
  { x: 5, y: 0 },
  { x: 6, y: 0.25 },
  { x: 7, y: 0.25 },

  { x: -7, y: 1.25 },
  { x: -6, y: 1.25 },
  { x: -5, y: 1 },
  { x: -4, y: 0.875 },
  { x: -3, y: 1 },
  { x: -2, y: 1.125 },
  { x: 2, y: 1.125 },
  { x: 3, y: 1 },
  { x: 4, y: 0.875 },
  { x: 5, y: 1 },
  { x: 6, y: 1.25 },
  { x: 7, y: 1.25 },
];

const corneKeys: KeyBinding[] = [
  { tap: 'Cut' },
  { tap: 'X' },
  { tap: 'V' },
  { tap: 'L' },
  { tap: 'C' },
  { tap: 'W' },
  { tap: 'Del' },
  { tap: 'Bksp' },
  { tap: 'K' },
  { tap: 'H' },
  { tap: 'G' },
  { tap: 'F' },
  { tap: 'Q' },
  { tap: 'ẞ' },

  { tap: 'Copy' },
  { tap: 'U' },
  { tap: 'I' },
  { tap: 'A' },
  { tap: 'E' },
  { tap: 'O' },
  { tap: 'Tab' },
  { tap: 'Enter' },
  { tap: 'S' },
  { tap: 'N' },
  { tap: 'R' },
  { tap: 'T' },
  { tap: 'D' },
  { tap: 'Y' },

  { tap: 'Paste' },
  { tap: 'Ü' },
  { tap: 'Ö' },
  { tap: 'Ä' },
  { tap: 'P' },
  { tap: 'Z' },
  { tap: 'B' },
  { tap: 'M' },
  { tap: ',', shifted: "–" },
  { tap: '.', shifted: "•" },
  { tap: 'J' },
  {},
];

export function Crkbd() {
  return <Keymap matrix={corneMatrix} keys={corneKeys} />;
}
